import type { BiDashboardConfig, BiField, BiWidgetConfig } from "./types";

export const BI_FIELD_LABELS: Record<BiField, string> = {
  anno: "Anno",
  mese: "Mese",
  cliente: "Cliente",
  categoria: "Categoria",
  tipo_prodotto: "Tipo prodotto",
  stato: "Stato",
  tipo: "Tipo record",
  numero_offerta: "Numero offerta",
  importo_preventivo: "Importo preventivo",
  importo_ordinato: "Importo ordinato",
  codice_articolo: "Codice articolo",
  descrizione: "Descrizione",
  quantita: "Quantita",
  prezzo_unitario: "Prezzo unitario",
  ricarico_pct: "Coeff. ricarico",
  totale_riga: "Totale riga",
};

export const DEFAULT_BI_WIDGETS: BiWidgetConfig[] = [
  {
    id: "kpi-preventivi",
    title: "Preventivi totali",
    type: "kpi",
    dataset: "documenti",
    x: 0,
    y: 0,
    w: 3,
    h: 2,
    metric: { op: "count", label: "Preventivi" },
  },
  {
    id: "kpi-valore",
    title: "Valore preventivi",
    type: "kpi",
    dataset: "documenti",
    x: 3,
    y: 0,
    w: 3,
    h: 2,
    metric: { op: "sum", field: "importo_preventivo", label: "Valore" },
  },
  {
    id: "kpi-medio",
    title: "Importo medio",
    type: "kpi",
    dataset: "documenti",
    x: 6,
    y: 0,
    w: 3,
    h: 2,
    metric: { op: "avg", field: "importo_preventivo", label: "Media" },
  },
  {
    id: "kpi-ore",
    title: "Ore preventivazione",
    type: "kpi",
    dataset: "documenti",
    x: 9,
    y: 0,
    w: 3,
    h: 2,
    metric: { op: "count", label: "Da tracciare" },
  },
  {
    id: "monthly-category",
    title: "Preventivi per mese e categoria",
    type: "stacked_bar",
    dataset: "documenti",
    x: 0,
    y: 2,
    w: 8,
    h: 4,
    metric: { op: "count", label: "Preventivi" },
    groupBy: "mese",
    stackBy: "categoria",
  },
  {
    id: "value-client",
    title: "Valore per cliente",
    type: "bar",
    dataset: "documenti",
    x: 8,
    y: 2,
    w: 4,
    h: 4,
    metric: { op: "sum", field: "importo_preventivo", label: "Valore" },
    groupBy: "cliente",
  },
  {
    id: "category-share",
    title: "Distribuzione categorie",
    type: "donut",
    dataset: "documenti",
    x: 0,
    y: 6,
    w: 4,
    h: 4,
    metric: { op: "count", label: "Preventivi" },
    groupBy: "categoria",
  },
  {
    id: "avg-month",
    title: "Importo medio mensile",
    type: "line",
    dataset: "documenti",
    x: 4,
    y: 6,
    w: 4,
    h: 4,
    metric: { op: "avg", field: "importo_preventivo", label: "Importo medio" },
    groupBy: "mese",
  },
  {
    id: "state-count",
    title: "Stato preventivi",
    type: "bar",
    dataset: "documenti",
    x: 8,
    y: 6,
    w: 4,
    h: 4,
    metric: { op: "count", label: "Preventivi" },
    groupBy: "stato",
  },
  {
    id: "top-articoli",
    title: "Top articoli per valore",
    type: "table",
    dataset: "righe_distinta",
    x: 0,
    y: 10,
    w: 12,
    h: 4,
    metric: { op: "sum", field: "totale_riga", label: "Valore" },
    groupBy: "codice_articolo",
  },
];

export const DEFAULT_BI_DASHBOARD: BiDashboardConfig = {
  version: 1,
  filters: [
    { field: "anno", op: "in", value: [2024, 2025, 2026] },
  ],
  widgets: DEFAULT_BI_WIDGETS,
};
